from grpc_book_service.utils.custom_exception import CustomException


class NotFound(CustomException):
    pass
